name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main
  # Allows you to trigger this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to grab all commit history
          lfs: true       # Tells git to fetch those large LFS objects

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # Update these exact two variables below with your HF handle and Space Name!
          HF_USERNAME: xplorers
          SPACE_NAME: MIS_API
        run: |
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          git push --force space main
